version: "3.8"

services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=kiwi_test
      - DB_USER=root
      - DB_PASSWORD=

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: kiwi_test
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  test:
    build:
      context: .
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=kiwi_test
      - DB_USER=root
      - DB_PASSWORD=pass
    entrypoint: ["./vendor/bin/phpunit"]

volumes:
  db_data:
